In [1]:
import numpy as np
import pandas as pd

Almost all functions that summarize or clean data default to axis=0. This is because Data Engineers usually want to know things about a "Feature" (Column) across all "Records" (Rows).

.drop() is the most common exception, for colm use axis=1

## "Axis 0 acts on Rows; Axis 1 acts on Columns."
#### act = smashing them down / act on / appling 

In [2]:
# Create a 3x3 grid
data = [[10, 20, 30, 39], 
        [40, 50, 60, 69], 
        [70, 80, 90, 99]]
df = pd.DataFrame(data, columns=['A', 'B', 'C', 'D'], index=['Row1', 'Row2', 'Row3'])
df  # shape=(3,4)

A   B   C   D
Row1  10  20  30  39
Row2  40  50  60  69
Row3  70  80  90  99

In [3]:
print(df.sum(axis=0))  # You fall down into it (Vertical)

A    120
B    150
C    180
D    207
dtype: int64


In [4]:
print(df.sum(axis=1))  # You walk along it (Horizontal)

Row1     99
Row2    219
Row3    339
dtype: int64


In [5]:
print(df.sum(axis=None))  # in future it will be single scaler(like numpy), 
                          # currently its same as 0, in pd better use axis=0 or dont use if not needed

A    120
B    150
C    180
D    207
dtype: int64


C:\Users\sk\AppData\Local\Temp\ipykernel_1828\1091491548.py:1: FutureWarning: The behavior of DataFrame.sum with axis=None is deprecated, in a future version this will reduce over both axes and return a scalar. To retain the old behavior, pass axis=0 (or do not pass axis)
  print(df.sum(axis=None))  # in future it will be single scaler(like numpy),


In [6]:
df_no_row = df.drop('Row1', axis=0)  # You fall down into it (Vertical) - DOESNT MAKE SENSE
df_no_row

A   B   C   D
Row2  40  50  60  69
Row3  70  80  90  99

In [7]:
df_no_col = df.drop('B', axis=1)  # find B in horizontal walk - DOESNT MAKE SENSE
df_no_col

A   C   D
Row1  10  30  39
Row2  40  60  69
Row3  70  90  99

In [8]:
df_no_row = df.max()  # default axis=0, You fall down into it (Vertical)
df_no_row

A    70
B    80
C    90
D    99
dtype: int64

In [9]:
result = df.max(axis=1)  # You walk along it (Horizontal)
result

Row1    39
Row2    69
Row3    99
dtype: int64

In [10]:
arr = np.array([[1, 2], [3, 4]])
arr

array([[1, 2],
       [3, 4]])

In [11]:
print(np.sum(arr, axis=0))  # You fall down into it (Vertical)

[4 6]


In [12]:
print(np.sum(arr, axis=1))  # find B in horizontal walk

[3 7]


In [13]:
print(np.sum(arr, axis=None))  # whole sum

10


### Now lets practice

In [14]:
a = np.array([[10, 2]])
b = np.array([[3, 40]])
a,b

(array([[10,  2]]), array([[ 3, 40]]))

In [15]:
c = np.concatenate( (a, b), axis=0 )
c

array([[10,  2],
       [ 3, 40]])

In [16]:
d = np.concatenate( (a, b), axis=1 )
d

array([[10,  2,  3, 40]])

In [17]:
df = pd.DataFrame({'Price': [100, 200], 'Tax': [10, 20]})
df

Price  Tax
0    100   10
1    200   20

In [18]:
df.apply(lambda row: row['Price'] + row['Tax'], axis=1)

0    110
1    220
dtype: int64

In [19]:
df.apply(lambda col: col.max(), axis=0)

Price    200
Tax       20
dtype: int64

In [20]:
from sklearn.preprocessing import normalize
X = np.array([[1, 10], 
              [2, 20]])
X

array([[ 1, 10],
       [ 2, 20]])

In [21]:
normalize(X, axis=1)  # walk along it

array([[0.09950372, 0.99503719],
       [0.09950372, 0.99503719]])

In [22]:
normalize(X, axis=0) 

array([[0.4472136 , 0.4472136 ],
       [0.89442719, 0.89442719]])

In [23]:
df = pd.DataFrame([[True, False], [True, True]], columns='C1 C2'.split())
df

C1     C2
0  True  False
1  True   True

In [24]:
df.any(axis=0)

C1    True
C2    True
dtype: bool

In [25]:
df.all(axis=1)

0    False
1     True
dtype: bool

In [26]:
import numpy as np

# Creating a 3D array (2 pages, 3 rows, 4 columns)
# Shape: (2, 3, 4)
data3d = np.arange(24).reshape(2, 3, 4)

print("Original 3D Array Shape:", data3d.shape)
data3d
# [ [[ 0  1  2  3], [ 4  5  6  7], [ 8  9 10 11]],  <-- Page 0
#   [[12 13 14 15], [16 17 18 19], [20 21 22 23]] ] <-- Page 1

Original 3D Array Shape: (2, 3, 4)


array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [27]:
page_sum = data3d.sum(axis=0) # Squish the Pages
# The 2 pages disappear. Result shape: (3, 4)
# Result: Page 0 + Page 1 (e.g., 0+12, 1+13...)
page_sum

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

In [28]:
row_totals = data3d.sum(axis=-1)  # same as axis=2 so where 4
# You go to the deepest level (the innermost list) and collapse the numbers.
row_totals

array([[ 6, 22, 38],
       [54, 70, 86]])

In [29]:
# The 3 rows disappear. Result shape: (2, 4)
col_max = data3d.max(axis=1)
col_max

array([[ 8,  9, 10, 11],
       [20, 21, 22, 23]])

In [30]:
# Transform
# Shape stays (2, 3, 4). Page 1 now includes Page 0's values.
running_total = data3d.cumsum(axis=0)
running_total

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 14, 16, 18],
        [20, 22, 24, 26],
        [28, 30, 32, 34]]])

In [31]:
import torch

# Create a 3D Tensor: 2 blocks, 3 rows, 4 columns
# Shape: [2, 3, 4]
x = torch.arange(24).reshape(2, 3, 4).float()
print(x)
# Example A: Squish the innermost dimension (Columns)
# Pointer -1 points to the 4.
result_a = x.sum(dim=-1)
print(result_a)
# Shape is now [2, 3]

tensor([[[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]],

        [[12., 13., 14., 15.],
         [16., 17., 18., 19.],
         [20., 21., 22., 23.]]])
tensor([[ 6., 22., 38.],
        [54., 70., 86.]])


In [32]:
# Example B: Softmax (Very common in AI)
# Softmax on dim=-1 makes all numbers in the innermost list add up to 1.0.
probs = torch.softmax(x, dim=-1)
print(probs)
# Example C: Concatenation
# Combining two tensors of shape [2, 3, 4]

tensor([[[0.0321, 0.0871, 0.2369, 0.6439],
         [0.0321, 0.0871, 0.2369, 0.6439],
         [0.0321, 0.0871, 0.2369, 0.6439]],

        [[0.0321, 0.0871, 0.2369, 0.6439],
         [0.0321, 0.0871, 0.2369, 0.6439],
         [0.0321, 0.0871, 0.2369, 0.6439]]])


In [33]:
y = torch.ones(2, 3, 4)
# dim=0: Stacks them to [4, 3, 4] (Double the pages)
# dim=1: Stacks them to [2, 6, 4] (Double the rows)
# dim=2: Stacks them to [2, 3, 8] (Double the columns)
combined = torch.cat((x, y), dim=1)
print(combined)

tensor([[[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 1.,  1.,  1.,  1.],
         [ 1.,  1.,  1.,  1.],
         [ 1.,  1.,  1.,  1.]],

        [[12., 13., 14., 15.],
         [16., 17., 18., 19.],
         [20., 21., 22., 23.],
         [ 1.,  1.,  1.,  1.],
         [ 1.,  1.,  1.,  1.],
         [ 1.,  1.,  1.,  1.]]])


## For numpy 3d operation - Caution: This is MADNESS

In [34]:
import numpy as np

# Create 3D data: Shape (2, 3, 4)
# Index 0: 2 (Pages)
# Index 1: 3 (Rows)
# Index 2: 4 (Columns)
data = np.arange(24).reshape(2, 3, 4)

print("--- ORIGINAL DATA (2, 3, 4) ---")
print(data)

--- ORIGINAL DATA (2, 3, 4) ---
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [35]:
# 1. AGGREGATION: Squish the dimension at the pointer
# axis=0: Squish the 2 pages into 1 (Stacking them)
sum_pages = data.sum(axis=0) # Result shape: (3, 4)
sum_pages

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

In [36]:
mean1 = data.mean(axis=1)
mean1

array([[ 4.,  5.,  6.,  7.],
       [16., 17., 18., 19.]])

In [37]:
max2 = data.max(axis=2)
max2

array([[ 3,  7, 11],
       [15, 19, 23]])

In [38]:
# 2. DELETION: Point to the dimension, then the slice index
# Delete the second page (index 1 of the 'Pages' dimension)
data_no_page = np.delete(data, 1, axis=0) # not inplace, creates new obj
data_no_page

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]])

In [39]:
data

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [40]:
data_del = np.delete(data, 0, axis=1)  # 0 is offset, so 0th row removed  !!? LITLLE CONFUSED AGAIN 🤯
data_del

array([[[ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [41]:
# 3. TRANSFORMATION: Move ALONG the dimension
# Accumulate values across pages (Page 0 + Page 1)
cum_sum = data.cumsum(axis=0)
cum_sum

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 14, 16, 18],
        [20, 22, 24, 26],
        [28, 30, 32, 34]]])

In [42]:
# 4. INSERTION: Create a gap in the dimension
# Insert a new "Page" of zeros at the beginning
new_page = np.zeros((1, 3, 4))
print(new_page)
data_plus_page = np.insert(data, obj=0, values=0, axis=0)  # obj -> index pointer, values 0 is broadcasted
print(data_plus_page)

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]
[[[ 0  0  0  0]
  [ 0  0  0  0]
  [ 0  0  0  0]]

 [[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [43]:
# 5. SELECTION: Take a specific slice
print(data)
res = np.take(data, -1, axis=-1)  # -1 means take last one
res

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


array([[ 3,  7, 11],
       [15, 19, 23]])

In [44]:
## So what i think i learned
# 0-> pages,
# 1-> rows,
# 2-> cols
# Axis (0, 1, 2) to a Physical Structure (Pages, Rows, Columns).

In [45]:
# so for 2d
# 0 -> rows
# 1 -> cols